name: Executar Scraper Polla

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar el Scraper
        run: python scraper.py

